name: Print Software Versions

on:
  push:
    branches: [main]

jobs:
  # Перша робота: Виводить версії програмного забезпечення на рівні обробки даних
  print_client_and_server_software_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Operating System (Client)
        run: uname -a  # Виводить версію ОС

      - name: Print Web Navigator (React)
        run: npx create-react-app --version  # Виводить версію React (як приклад веб-навігатора)

      - name: Print Java Version (Server)
        run: java -version  # Виводить версію Java

  # Друга робота: Виводить версії СУБД на рівні доступу до даних
  print_database_server_version:
    runs-on: ubuntu-latest
    needs: [print_client_and_server_software_versions]
    steps:
      - name: Print PostgreSQL Version
        run: psql --version  # Виводить версію PostgreSQL
